colegios/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('app.inicio.urls')),
    url(r'^', include('app.login.urls')),
    url(r'^', include('app.institucional.urls')),
    url(r'^', include('app.categoria.urls')),
    url(r'^', include('app.contentcategoria.urls')),
    url(r'^', include('app.usuario.urls')),
    url(r'^', include('app.docente.urls')),
    url(r'^api/', include('app.api.urls')),

    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/inicio/models.py
from django.contrib.auth.models import User
from django.db import models
from random import randint


class Profile(models.Model):
    def ImageProfile(self, filename):
        return "media/img/usuarios/%s-%s" % (randint(99999, 999999), filename)

    roles = ((1, "Administrador"), (2, "Docente"), (3, "Acudiente"),)

    rol = models.IntegerField(choices=roles)
    # cedula = models.CharField(max_length=144)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=144)

    # otros atributos requeridos
    foto = models.ImageField(upload_to=ImageProfile,
                             default="media/img/usuarios/adefault.png")
    facebook = models.CharField(max_length=144,
                                blank=True, null=True)
    twitter = models.CharField(max_length=144,
                               blank=True, null=True)

    user = models.OneToOneField(User)

    class Meta:
        db_table = 'profile'

    def __str__(self):
        return self.user.first_name


class Categorias(models.Model):
    tipo = models.IntegerField(choices=(
        (1, "Grupo"),
        (2, "Electiva"),
    ))
    categoria = models.CharField(max_length=144)

    class Meta:
        db_table = 'categorias'

    def __str__(self):
        return self.categoria


class Contenido(models.Model):
    fecha = models.DateTimeField(auto_now=True)
    titulo = models.CharField(max_length=144)
    grupo = models.ForeignKey(Categorias)
    contenido = models.TextField(blank=True)
    autor = models.ForeignKey(Profile)
    class Meta:
        db_table = 'contenido'

    def __str__(self):
        return self.titulo


class Megusta(models.Model):
    user = models.ForeignKey(Profile)
    contenido = models.ForeignKey(Contenido)
    class Meta:
        db_table = 'me_gusta'


class Galeria(models.Model):
    def uploadImg(self, filename):
        return "media/image/%s" % filename

    imagen = models.ImageField(upload_to=uploadImg)
    contenido = models.ForeignKey(Contenido)

    class Meta:
        db_table = 'galeria'

    def __str__(self):
        return str(self.imagen)


class Docentes(models.Model):
    user = models.OneToOneField(User)
    categorias = models.ManyToManyField(Categorias)
    class Meta:
        db_table = 'docentes'


class Estudiantes(models.Model):
    estudiante = models.CharField(max_length=144)
    categoria = models.ForeignKey(Categorias)
    electivas = models.ManyToManyField(Categorias,
                                       related_name="eleconcate")
    acudiente = models.ForeignKey(Profile)

    class Meta:
        db_table = 'estudiantes'

    def __str__(self):
        return self.estudiante


class Notificaciones(models.Model):
    fechayhora = models.DateTimeField(auto_now=True)
    contenido = models.TextField()
    categoria = models.ForeignKey(Categorias)
    estudiantes = models.ManyToManyField(Estudiantes)
    remitente = models.ForeignKey(Profile)

    class Meta:
        db_table = 'notificaciones'


class Tokens(models.Model):
    device = models.CharField(max_length=144)
    plataforma = models.IntegerField(choices=(
        (1, "Android"),
        (2, "iOS"),
    ))
    token = models.CharField(max_length=244)
    acudiente = models.ForeignKey(Profile)

    class Meta:
        db_table = 'tokens'


class Institucional(models.Model):
    colegio = models.CharField(max_length=144)
    direccion = models.CharField(max_length=144)
    telefono = models.IntegerField()
    horarios = models.TextField()
    ciudad = models.CharField(max_length=144)
    email = models.EmailField()
    facebook = models.CharField(max_length=144)
    twitter = models.CharField(max_length=144)

    class Meta:
        db_table = 'institucional'

templates/partials/alumnosform.html
    <div class="card">
                 <div class="card-head style-primary-light">
                            <header>Alumnos asociados al representante <small>Alumnos, Hijos, representados</small></header>
                 </div>
                    <div class="card-body">

                        <div class="form">
                            {{ formset.management_form }}
                            {% for form in formset %}
                                <div class="table">
                                    {{ form }}
                                </div>
                            {% endfor %}
                            <div class=" text-right">
                                <button id="remove_estu" class="btn btn-danger btn-raised" type="button">Eliminar formulario</button>
                                <button id="add_estu" class="btn btn-primary-light btn-raised" type="button   ">Agregar alumno</button>
                                <button class="btn btn-primary btn-raised" type="submit">Guardar Todo</button>
                            </div>
                        </div>
                    </div>
                </div>
    </div>

templates/partials/contenidolist.html
{% comment %} <section>
        <div class="section-body contain-lg">

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">{% endcomment %}
                            <form class="form">
                                <section class="style-default-bright">

                                    <div class="section-body">
                                        <div class="row">

                                            <div class="col-lg-12">
                                                <div class="table-responsive">
                                                    <table id="datatable1" class="table table-striped table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Fecha</th>
                                                                <th>Titulo</th>
                                                                <th>Contenido</th>
                                                                <th>Me Gusta</th>

                                                                <th class="sort-alpha ">Opciones</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for c in cs %}
                                                            <tr class="gradeX">
                                                                <td>{{ c.fecha|date:"d M Y" }}</td>
                                                                <td>{{ c.titulo }}</td>
                                                                <td>{{ c.contenido|truncatechars:55  }}</td>
                                                                <td align="center">{{ c.megusta_set.count }} <i class="fa fa-heart" aria-hidden="true" style="color: #aa0000;"></i></td>
                                                                <td align="center" valign="middle">
                                                                     <a href="{% url 'cateConteEditView' idcate=c.grupo.id idconte=c.id %}">
                                                                        <button type="button" class="btn btn-warning btn-raised boton_tabla"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                                                     </a>

              {% comment %}                                                       <a href="{% url 'cateConteVerDetalleView' idcate=c.grupo.id idconte=c.id %}">
                                                                        <button  class="btn btn-warning btn-raised boton_tabla" type="button">
                                                                            <i class="fa fa-binoculars" aria-hidden="true"></i></button>
                                                                    </a>{% endcomment %}

                                                                    <a class="delcontent" data-value="{{ c.id}}">
                                                                        <button type="button" class="btn btn-danger btn-raised boton_tabla" ><i class="fa fa-trash" aria-hidden="true"></i></button>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </form>
  {% comment %}                        </div>
                    </div><!-- card -->
              </div>
            </div>

        </div>
</section>{% endcomment %}

templates/partials/notifylist.html
{% comment %} <section>
        <div class="section-body contain-lg">

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">{% endcomment %}
                            <form class="form">
                                <section class="style-default-bright">

                                    <div class="section-body">
                                        <div class="row">

                                            <div class="col-lg-12">
                                                <div class="table-responsive">
                                                    <table id="datatable1" class="table table-striped table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Fecha</th>
                                                                <th>Grupo</th>
                                                                <th>Notificacion</th>

                                                                <th class="sort-alpha ">Opciones</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for n in ns %}
                                                            <tr class="gradeX">
                                                                <td width="20%">{{ n.fechayhora|date:"d M Y" }}</td>
                                                                <td> {{ n.categoria }}</td>
                                                                <td>{{ n.contenido|truncatechars:18  }}</td>
                                                                <td align="center" valign="middle">
                                                                    <a href="{% url 'notifyDetalleview' idnoti=n.id %}">
                                                                        <button  class="btn btn-primary btn-raised boton_tabla" type="button"><i class="fa fa-binoculars" aria-hidden="true"></i></button>
                                                                    </a>
{##}
{#								                                    <a href="{% url 'cambiarclave' user=d.user.id rol='docentes' %}">#}
{#                                                                        <button type="button" class="btn btn-warning btn-raised boton_tabla"><i class="fa fa-key" aria-hidden="true"></i></button>#}
{#                                                                    </a>#}

                                                                    <a class="delnoti" data-value="{{ n.id}}">
                                                                        <button type="button" class="btn btn-danger btn-raised boton_tabla" ><i class="fa fa-trash" aria-hidden="true"></i></button>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </form>
  {% comment %}                        </div>
                    </div><!-- card -->
              </div>
            </div>

        </div>
</section>{% endcomment %}

templates/partials/usuariologinform.html
{% load addform %}


            <div class="form">
                <div class="card">
                            {{ ucform.errors }}
                            {{ pform.errors }}

                        <div class="card-head ">
                            <header>Datos para Iniciar sesión  | Padre - Representante <small> usada por los padres desde la App</small></header>
                        </div>
                         <div class="card-body">

                            <div class="form-group">
                                <span class="input-group-addon"><i class="fa fa-at" aria-hidden="true"></i>
                                </span>
                                <div class="input-group-content">
                                    {{ ucform.username|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Email (Éste será el usuario con el que iniciará sesión)</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <span class="input-group-addon"><i class="fa fa-unlock-alt" aria-hidden="true"></i>
                                </span>
                                <div class="input-group-content">
                                    {{ ucform.password }}

                                    {{ ucform.password1|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Contraseña</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <span class="input-group-addon"><i class="fa fa-unlock-alt" aria-hidden="true"></i>
                                </span>
                                <div class="input-group-content">
                                    {{ ucform.password2|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Repite contraseña</label>
                                </div>
                            </div>
                         </div>
                </div>
            </div>
        </div>

templates/partials/usuarioprofileform.html
{% load addform %}



            <div class="form">
                <div class="card">
                   <div class="card-head style-primary-light">
                            <header>Información de Padre | Representante <small> Detalles del usuario, padre o representante</small></header>
                   </div>
                            {{ ucform.errors }}
                            {{ pform.errors }}
                        <div class="card-body">


                              <div class="form-group col-sm-2 style-primary-light">
                                <div class="checkbox checkbox-styled">
                                    <label>
                                            {{ ucform.is_active  }}
									    <span class="span_title"></span>
								    </label>
                                </div>
                            </div>

                            <div class="form-group col-sm-5">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-child" aria-hidden="true"></i>
                                    </span></span>
                                <div class="input-group-content">
                                    {{ ucform.first_name|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Nombres</label>
                                </div>

                            </div>
                            <div class="form-group col-sm-5">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-child" aria-hidden="true"></i>
                                    </span></span>
                                <div class="input-group-content">
                                    {{ ucform.last_name|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Apellidos</label>
                                </div>

                            </div>
    {% comment %}                        <div class="form-group">
                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-graduation-cap" aria-hidden="true"></i>
                                </span></span>
                                <div class="input-group-content">
                                    {{ ucform.email.as_hidden|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Correo</label>
                                </div>
                            </div>{% endcomment %}
                            {{ ucform.email.as_hidden|add:'class="form-control" id="username9"' }}
			    <!--
                            <div class="form-group">
                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-list-alt" aria-hidden="true"></i>
                                    </span></span>
                                <div class="input-group-content">
                                    <label for="username9">Número de identificación</label>
                                </div>
                            </div>-->

                            <div class="form-group">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-phone" aria-hidden="true"></i>
                                    </span></span>
                                <div class="input-group-content">
                                    {{ pform.telefono|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Telefono</label>
                                </div>

                            </div>
                            <div class="form-group">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"></span><i class="fa fa-building" aria-hidden="true"></i>
                                    </span>
                                <div class="input-group-content">
                                    {{ pform.direccion|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Dirección</label>
                                </div>

                            </div>

                            <div class=" text-right">
                                <button class="btn btn-primary btn-raised" type="submit">Guardar</button>
                            </div>
			    <!--
                            <div class="form-group">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"></span><i class="fa fa-building" aria-hidden="true"></i>
                                    </span>
                                <div class="input-group-content">
                                    {{ pform.facebook|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Facebook</label>
                                </div>

                            </div>

                            <div class="form-group">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"></span><i class="fa fa-building" aria-hidden="true"></i>
                                    </span>
                                <div class="input-group-content">
                                    {{ pform.twitter|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Twitter</label>
                                </div>

                            </div> -->

                        </div>
                </div>
            </div>