app/categoria/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^grupos/$', views.categoriaVerView, name="categoriaVerView"),
    url(r'^grupos/agregar/', views.categoriaAddView, name="categoriaAdd"),
    url(r'^grupos/eliminar/', views.categoriaBorrar, name="categoriaBorrar"),
    url(r'^grupos/(?P<idcate>[0-9]+)/$', views.categoriaEditView, name="categoriaEditView"),

]

app/docente/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # docentes
    url(r'^docentes/$', views.docentesVerView, name="docentesVerView"),
    url(r'^docentes/agregar/$', views.docentesAddView, name="docentesAddView"),
    url(r'^docentes/(?P<doce>[0-9]+)/', views.docentesEditView, name="docentesEditView"),


]

app/usuario/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # usuarios
    url(r'^usuarios/$', views.usuariosVerView, name="usuariosVerView"),
    url(r'^usuarios/agregar/', views.usuariosAddView, name="usuariosAddView"),
    url(r'^usuarios/(?P<idpro>[0-9]+)/', views.usuariosEditView, name="usuariosEditView"),
]

colegios/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('app.inicio.urls')),
    url(r'^', include('app.login.urls')),
    url(r'^', include('app.institucional.urls')),
    url(r'^', include('app.categoria.urls')),
    url(r'^', include('app.contentcategoria.urls')),
    url(r'^', include('app.usuario.urls')),
    url(r'^', include('app.docente.urls')),
    url(r'^api/', include('app.api.urls')),

    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/categoria/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app/docente/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app/inicio/models.py
from django.contrib.auth.models import User
from django.db import models
from random import randint


class Profile(models.Model):
    def ImageProfile(self, filename):
        return "media/img/usuarios/%s-%s" % (randint(99999, 999999), filename)

    roles = ((1, "Administrador"), (2, "Docente"), (3, "Acudiente"),)

    rol = models.IntegerField(choices=roles)
    # cedula = models.CharField(max_length=144)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=144)

    # otros atributos requeridos
    foto = models.ImageField(upload_to=ImageProfile,
                             default="media/img/usuarios/adefault.png")
    facebook = models.CharField(max_length=144,
                                blank=True, null=True)
    twitter = models.CharField(max_length=144,
                               blank=True, null=True)

    user = models.OneToOneField(User)

    class Meta:
        db_table = 'profile'

    def __str__(self):
        return self.user.first_name


class Categorias(models.Model):
    tipo = models.IntegerField(choices=(
        (1, "Grupo"),
        (2, "Electiva"),
    ))
    categoria = models.CharField(max_length=144)

    class Meta:
        db_table = 'categorias'

    def __str__(self):
        return self.categoria


class Contenido(models.Model):
    fecha = models.DateTimeField(auto_now=True)
    titulo = models.CharField(max_length=144)
    grupo = models.ForeignKey(Categorias)
    contenido = models.TextField(blank=True)
    autor = models.ForeignKey(Profile)
    class Meta:
        db_table = 'contenido'

    def __str__(self):
        return self.titulo


class Megusta(models.Model):
    user = models.ForeignKey(Profile)
    contenido = models.ForeignKey(Contenido)
    class Meta:
        db_table = 'me_gusta'


class Galeria(models.Model):
    def uploadImg(self, filename):
        return "media/image/%s" % filename

    imagen = models.ImageField(upload_to=uploadImg)
    contenido = models.ForeignKey(Contenido)

    class Meta:
        db_table = 'galeria'

    def __str__(self):
        return str(self.imagen)


class Docentes(models.Model):
    user = models.OneToOneField(User)
    categorias = models.ManyToManyField(Categorias)
    class Meta:
        db_table = 'docentes'


class Estudiantes(models.Model):
    estudiante = models.CharField(max_length=144)
    categoria = models.ForeignKey(Categorias)
    electivas = models.ManyToManyField(Categorias,
                                       related_name="eleconcate")
    acudiente = models.ForeignKey(Profile)

    class Meta:
        db_table = 'estudiantes'

    def __str__(self):
        return self.estudiante


class Notificaciones(models.Model):
    fechayhora = models.DateTimeField(auto_now=True)
    contenido = models.TextField()
    categoria = models.ForeignKey(Categorias)
    estudiantes = models.ManyToManyField(Estudiantes)
    remitente = models.ForeignKey(Profile)

    class Meta:
        db_table = 'notificaciones'


class Tokens(models.Model):
    device = models.CharField(max_length=144)
    plataforma = models.IntegerField(choices=(
        (1, "Android"),
        (2, "iOS"),
    ))
    token = models.CharField(max_length=244)
    acudiente = models.ForeignKey(Profile)

    class Meta:
        db_table = 'tokens'


class Institucional(models.Model):
    colegio = models.CharField(max_length=144)
    direccion = models.CharField(max_length=144)
    telefono = models.IntegerField()
    horarios = models.TextField()
    ciudad = models.CharField(max_length=144)
    email = models.EmailField()
    facebook = models.CharField(max_length=144)
    twitter = models.CharField(max_length=144)

    class Meta:
        db_table = 'institucional'

app/institucional/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app/usuario/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app/inicio/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from pyfcm import FCMNotification
from django.conf import settings
push_service = FCMNotification(api_key=settings.FBCM_API_KEY)

from app.inicio.models import Categorias, Profile, Estudiantes, Notificaciones, Institucional, Contenido, Galeria, \
    Docentes, Tokens


class loginForm(AuthenticationForm):
    pass

class usercreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", )

class userchangeForm(UserChangeForm):
    class Meta:
        model = User
        exclude = ['username', 'date_joined']

class docentesCreateForm(forms.ModelForm):
    class Meta:
        model = Docentes
        fields = ('categorias',)

class categoriasForm(forms.ModelForm):
    class Meta:
        model = Categorias
        fields = '__all__'


class profileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('telefono', 'direccion', 'foto', )


class EstudiantesForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(queryset=Categorias.objects.filter(tipo=1),
                                       widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'}))
    electivas = forms.ModelMultipleChoiceField(queryset=Categorias.objects.filter(tipo=2),
                                               required=False,
                                               widget=forms.SelectMultiple(attrs={'class': 'form-control'}))

    class Meta:
        model = Estudiantes
        fields = ('estudiante', 'categoria', 'electivas', )
        widgets = {
            'estudiante': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
        }
        labels = {
            'estudiante': 'alumno',
        }

class NotificacionesForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super(NotificacionesForm, self).__init__(*args, **kwargs)

        if request is not None:
            if request.user.profile.rol == 2:
                self.fields["categoria"] = forms.ModelChoiceField(queryset=request.user.docentes.categorias.all())

    def send_push(self):
        ts = Tokens.objects.raw('SELECT `tokens`.`id`, `tokens`.`device`, `tokens`.`plataforma`, `tokens`.`token`, `tokens`.`acudiente_id` '\
                                    'FROM `estudiantes` '\
                                    'INNER JOIN `notificaciones_estudiantes` ON (`estudiantes`.`id` = `notificaciones_estudiantes`.`estudiantes_id`) '\
                                    'INNER JOIN `tokens` ON(`tokens`.`acudiente_id` = `estudiantes`.`acudiente_id`) '\
                                    'WHERE `notificaciones_estudiantes`.`notificaciones_id` = {0}'.format(self.noti.id))
        mtokens = [(t.token) for t in ts]
        if len(mtokens) > 0:
            payload = {
                "type": "Notificacion",
                "user_id": self.noti.remitente.user.id,
                "user": self.noti.remitente.user.get_full_name(),
                "foto": self.noti.remitente.user.profile.foto.name,
                "message": self.noti.contenido,
                "priority": "high",
                "content_available": "true",
                "click_action": "OPEN_ACTIVITY_1"
            }
            return push_service.notify_multiple_devices(registration_ids=mtokens, message_body=self.noti.contenido, data_message=payload, sound="default", )

    def save(self, commit=True):
        self.noti = super(NotificacionesForm, self).save(commit=False)
        if commit:
            self.noti.save()
            self.noti.save_m2m()
        return self.noti

    class Meta:
        model = Notificaciones
        fields = ("contenido", "categoria", "estudiantes", )

class InstitucionalForm(forms.ModelForm):
    class Meta:
        model = Institucional
        fields = '__all__'


class ContenidoForm(forms.ModelForm):
    class Meta:
        model = Contenido
        fields = ('titulo','contenido',)


class GaleriaForm(forms.ModelForm):
    class Meta:
        model = Galeria
        fields = ('imagen', 'contenido', )

app/categoria/views.py
# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')

from django.contrib.auth.decorators import login_required
from app.inicio.forms import  categoriasForm
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect, JsonResponse, Http404
from django.core.urlresolvers import reverse
from app.inicio.models import Categorias

@login_required(login_url="/login")
def categoriaAddView(request):
    if request.user.profile.rol == 1:
        if request.method == 'POST':
            cform = categoriasForm(request.POST)
            if cform.is_valid():
                cform.save()
                return HttpResponseRedirect(reverse('categoriaVerView'))
        else:
            cform = categoriasForm()
        return render(request, "categoriasadd.html", { "cform": cform })
    raise Http404

@login_required(login_url="/login")
def categoriaEditView(request, idcate):
    if request.user.profile.rol == 1:
        c = get_object_or_404(Categorias, id=idcate)
        if request.method == 'POST':
            cform = categoriasForm(data=request.POST, instance=c)
            if cform.is_valid():
                cform.save()
                return HttpResponseRedirect(reverse('categoriaVerView'))
        else:
            cform = categoriasForm(instance=c)
        return render(request, "categoriasadd.html", {"cform": cform,
                                                      "modo": "edit",
                                                      "cate": c.id })
    raise Http404

@login_required(login_url="/login")
def categoriaVerView(request):
    if request.user.profile.rol == 1:
        cs = Categorias.objects.all()
    elif request.user.profile.rol == 2:
        cs = request.user.docentes.categorias.all()
    else:
        raise Http404
    return render(request, "categorias.html", { "cs": cs })

@login_required(login_url="/login")
def categoriaBorrar(request):
    if request.method == "POST" and request.is_ajax():
        try:
            c = Categorias.objects.get(id=request.POST.get("cate"))
            c.delete()
        except:
            return JsonResponse({"status": "ERRORS"})
        return JsonResponse({"status": "OK"})
    raise Http404

app/docente/views.py
# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from app.inicio.forms import profileForm, usercreateForm,  userchangeForm,   docentesCreateForm
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect,  Http404
from django.core.urlresolvers import reverse
from app.inicio.models import Docentes


@login_required(login_url="/login")
def docentesVerView(request):
    if request.user.profile.rol == 1:
        ds = Docentes.objects.all()
        return render(request, "docentes.html", { "ds": ds })
    else:
        c = get_object_or_404(User, id=request.user.profile.id)
        print c.first_name
        return render(request, "docentes_main/main.html",{"c":c})


@login_required(login_url="/login")
def docentesAddView(request):
    if request.user.profile.rol == 1:
        if request.method == 'POST':
            ucform = usercreateForm(request.POST)
            pform = profileForm(request.POST)
            dcform = docentesCreateForm(request.POST)

            if pform.is_valid() and ucform.is_valid() and dcform.is_valid():
                payload = ucform.save()
                # guardamos el perfil del usuario
                rpform = pform.save(commit=False)
                rpform.user_id = payload.id
                rpform.rol = 2  # id rol docente
                rpform.save()
                # guardamos al docente y su grupo
                rdcform = dcform.save(commit=False)
                rdcform.user_id = payload.id
                rdcform.save()
                dcform.save_m2m()

                # guardamos los estudiantes
                return HttpResponseRedirect(reverse("docentesVerView"))
        else:
            ucform = usercreateForm()
            pform = profileForm()
            dcform = docentesCreateForm()
        return render(request, "docentesadd.html", { "ucform": ucform, "pform": pform, "dcform": dcform })
    raise Http404


@login_required(login_url="/login")
def docentesEditView(request, doce):
    if request.user.profile.rol == 1:
        ds = get_object_or_404(Docentes, id=doce)
        if request.method == 'POST':
            ucform = userchangeForm(data=request.POST, instance=ds.user)
            pform = profileForm(request.POST, request.FILES, instance=ds.user.profile)
            dcform = docentesCreateForm(data=request.POST, instance=ds)

            if ucform.is_valid():
                payload = ucform.save()
            if pform.is_valid():
                # guardamos el perfil del usuario
                rpform = pform.save(commit=False)
                rpform.user_id = ds.user.id
                rpform.rol = 2  # id rol docente
                rpform.save()
            if dcform.is_valid():
                # guardamos al docente y los grupos
                rdcform = dcform.save(commit=False)
                rdcform.user_id = ds.user.id
                rdcform.save()
                dcform.save_m2m()

            return HttpResponseRedirect(reverse("docentesVerView"))
        else:
            ucform = userchangeForm(instance=ds.user)
            pform = profileForm(instance=ds.user.profile)
            dcform = docentesCreateForm(instance=ds)
        return render(request, "docentesadd.html", { "ucform": ucform, "pform": pform,
                                                     "dcform": dcform, "modo": "edit" })
    raise Http404

app/institucional/views.py
# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')

from django.contrib.auth.decorators import login_required
from app.inicio.forms import  InstitucionalForm
from django.shortcuts import render
from django.http.response import HttpResponseRedirect,  Http404
from django.core.urlresolvers import reverse
from app.inicio.models import Institucional

# Create your views here.
@login_required(login_url="/login")
def institucionalView(request):
    if request.user.profile.rol == 1:
        n = Institucional.objects.first()
        if request.method == 'POST':
            nform = InstitucionalForm(data=request.POST, instance=n)
            if nform.is_valid():
                nform.save()
                return HttpResponseRedirect(reverse("institucionalView"))
        else:
            nform = InstitucionalForm(instance=n)
        return render(request, "institucional.html", { "nform": nform })
    raise Http404

templates/categoriasadd.html
{% extends "base.html" %}
{% load addform %}
{% block title %}Categorias - Agregar{% endblock %}
{% block js %}
<script type="text/javascript">
    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $("#eliminar").click(function() {
        if(confirm("Deseas eliminar esta categoria")) {
            $.ajax({
                url: "{% url 'categoriaBorrar' %}",
                method: "POST",
                data: { cate : $(this).attr("data-value") },
                dataType: "json"
            }).done(function(result) {
                if(result.status == "OK") {
                    alert("Categoria Borrrada con exito");
                    location.href="{% url 'categoriaVerView' %}";
                }
            });
        }
    });

</script>
{% endblock %}
{% block content %}
<section>
    <div class="section-body contain-lg">

        <div class="row">
            <div class="col-lg-6 col-centered">
                <div class="card">
                    <div class="card-body">
                        <form action="." class="form" method="post">
                            {% csrf_token %}
                            <div class="text-center">
                                <h2>{% if modo == "edit" %} Editar {% else %} Agregar {% endif %}Grupo</h2>
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    {{ cform.tipo|add:'class="form-control" id="placeholder1" placeholder="Categoria Nueva"' }}
                                </div>
                                <div class="form-group">
                                    {{ cform.categoria|add:'class="form-control" id="placeholder1" placeholder="Grupo nuevo"' }}
                                </div>
                            </div>
                            <div >
                                <div class="col-md-6">
                                    <button class="btn btn-primary btn-raised" type="submit">Guardar</button>
                                    {% if modo == "edit" %}
                                    <button id="eliminar" data-value="{{ cate }}" class="btn btn-danger btn-raised" type="button">Eliminar</button>
                                    {% endif %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
{% endblock %}

templates/docentesadd.html
{% extends "base.html" %}
{% load addform %}
{% block title %}Docentes - agregar{% endblock %}
{% block css %}
<link href="/media/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">
<style type="text/css">
    #ms-id_categorias {
        width: 100%;
    }
    .search-input {
        width: 100%;
    }
</style>
{% endblock %}
{% block js %}
<script src="/media/js/jquery.multi-select.js" type="text/javascript"></script>
<script src="/media/js/jquery.quicksearch.js" type="text/javascript"></script>
<script type="text/javascript">
    $('#id_categorias').multiSelect({
        selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Grupos'>",
        selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Mis grupos'>",
        afterInit: function(ms){
            var that = this,
            $selectableSearch = that.$selectableUl.prev(),
            $selectionSearch = that.$selectionUl.prev(),
            selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
            selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

            that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
            .on('keydown', function(e){
              if (e.which === 40){
                that.$selectableUl.focus();
                return false;
            }
        });

            that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
            .on('keydown', function(e){
              if (e.which == 40){
                that.$selectionUl.focus();
                return false;
            }
        });
        },
        afterSelect: function(){
            this.qs1.cache();
            this.qs2.cache();
        },
        afterDeselect: function(){
            this.qs1.cache();
            this.qs2.cache();
        }
    });
    $(document).ready(function() {
        var src = $("#id_foto").parent().find("a").attr("href");
        $("#id_foto").parent().find("a").remove();
        if(src != undefined){
            $("#id_foto").parent().prepend("<img src='/"+src+"' width=140 />");
        }


        if ($('input#id_is_active').prop('checked')) {
             $('.span_title').text('Activo');
        }else{
              $('.span_title').text('Desactivado');
        }


            $("#id_username").change(function(){
               // alert($("#id_username").val());
                $('#id_email').val($(this).val());
        });


         $('input#id_is_active').change(function() {
                if ($('input#id_is_active').prop('checked')) {
                        $('.span_title').text('Activo');
                }else{
                      $('.span_title').text('Desactivado');
                }
        });

    });


</script>
{% endblock %}
{% block content %}
<section>
    <div class="section-body contain-lg">

        <div class="row">
            <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="col-lg-8 col-centered">


                {% if modo != "edit" %}
                <div class="card">
                    <div class="card-body">
                        <div class="form">
                            <div class="text-center">
                                <h2>Cuenta del docente</h2>
                            </div>

                            <div class="form-group">
                                <span class="input-group-addon"><i class="fa fa-at" aria-hidden="true"></i>
                                </span>
                                <div class="input-group-content">
                                    {{ ucform.username|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Email (Éste será el usuario con el que iniciará sesión)</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <span class="input-group-addon"><i class="fa fa-unlock-alt" aria-hidden="true"></i>
                                </span>
                                <div class="input-group-content">
                                    {{ ucform.password }}

                                    {{ ucform.password1|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Contraseña</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <span class="input-group-addon"><i class="fa fa-unlock-alt" aria-hidden="true"></i>
                                </span>
                                <div class="input-group-content">
                                    {{ ucform.password2|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Repite contraseña</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}




                <div class="card">
                     <div class="card-head style-primary-light">
                            <header>Información del docente <small> Detalles de grupos asignados</small>

                            </header>
                   </div>
                    <div class="card-body">
                        <div class="form">

                            {{ ucform.errors }}
                            {{ pform.errors }}

                            <div class="form-group col-sm-2 style-primary-light">
                              <div class="checkbox checkbox-styled">
														<label>
															 {{ ucform.is_active  }}
															<span class="span_title"></span>
														</label>
													</div>
                            </div>
                            <div class="form-group col-sm-5">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-child" aria-hidden="true"></i>
                                    </span></span>
                                <div class="input-group-content">
                                    {{ ucform.first_name|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Nombres</label>

                                </div>

                            </div>
                            <div class="form-group col-sm-5">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-child" aria-hidden="true"></i>
                                    </span></span>
                                <div class="input-group-content">
                                    {{ ucform.last_name|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Apellidos</label>
                                </div>

                            </div>
            {% comment %} <div class="form-group">
                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-graduation-cap" aria-hidden="true"></i>
                                </span></span>
                                <div class="input-group-content">
                                    {{ ucform.email|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Correo</label>
                                </div>
                            </div>% endcomment %}
                            {{ ucform.email.as_hidden|add:'class="form-control" id="username9"' }}
                            <div class="form-group">
                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-graduation-cap" aria-hidden="true"></i>
                                </span></span>
                                <div class="input-group-content">
                                    {{ pform.foto }}
                                    <label for="username9">Foto</label>
                                </div>
                            </div>
                
                            <div class="form-group">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"><i class="fa fa-phone" aria-hidden="true"></i>
                                    </span></span>
                                <div class="input-group-content">
                                    {{ pform.telefono|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Telefono</label>
                                </div>

                            </div>
                            <div class="form-group">

                                <span class="input-group-addon"><span class="glyphicon  fa-lg"></span><i class="fa fa-building" aria-hidden="true"></i>
                                    </span>
                                <div class="input-group-content">
                                    {{ pform.direccion|add:'class="form-control" id="username9"' }}
                                    <label for="username9">Dirección</label>
                                </div>

                            </div>
             
                        </div>
                    </div>
                </div>

                               <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            <h2>Grupos</h2>
                        </div>
                        <div class="form">
                            {{ dcform.categorias }}
                        </div>
                    </div>
                </div>

                <div class=" text-right">
                    <button class="btn btn-primary btn-raised" type="submit">Guardar docente</button>
                </div>
            </div>

            
        </form>
        </div>
    </div>
</section>
{% endblock %}